version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: anael-nocodb_server_1
      APP_PORT: 8080

  server:
    image: nocodb/nocodb:v0.262.5@sha256:3478bce1f128d46eb9d4a838cf2ce320693750a785aad6efa8de3235ab3733c5
    volumes:
      - ${APP_DATA_DIR}/data:/usr/app/data
    environment:
      - PUID=1000
      - PGID=1000
    restart: on-failure
