version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: anael-nocodb_server_1
      APP_PORT: 8080

  server:
    image: nocodb/nocodb:v0.262.2@sha256:75c718b3a5ab713b8c32f896de281e21232ca01cd3d9be354af77d5f764e1202
    volumes:
      - ${APP_DATA_DIR}/data:/usr/app/data
    environment:
      - PUID=1000
      - PGID=1000
    restart: on-failure
